### ISSUE TITLE
param -peers not working

### ISSUE THREAD

**Issue by Bodyash** [en9inerd/tgeraser#10]
-peers PEER_ID  Specify certain peers by comma (chat/channel/user).

Tried to use this param.
tgeraser session test -peers 1,2,3...
It didn't worked. Got something like peer id 1 isn't found or something like this.

Probably program is trying to process peers specified in param before loading available peers from telegram server.

**Comment by en9inerd** [comment]
@Bodyash peer id isn't the entity number from list of entities/dialogs, it's id of specific telegram user/chat/channel - https://core.telegram.org/type/Peer

**Comment by en9inerd** [comment]
@Bodyash if correct peer ids (or usernames if it's public chat/channel/user) are specified then the reason why the error appears may be [this](https://stackoverflow.com/questions/75803858/what-is-access-hash-in-telegram-api). In this case entity with specified peer id should be cached by telethon before you can do something with that entity. Telethon stores the entity data (it includes access_hash and other things) inside its session file. So, you can just execute `tgeraser session test --entity-type any` command to cache all entities from list of dialogs and after that you can exit by CTRL+C and use command with `--peers` param.

Note: just in case, it's not possible to use peer ids that are not into your list of dialogs.

**Comment by Bodyash** [comment]
> @Bodyash peer id isn't the entity number from list of entities/dialogs, it's id of specific telegram user/chat/channel - https://core.telegram.org/type/Peer

Got it, I've checked ids from entities and tried to use them. I will try to do the same with telegram ids, thx!
