### ISSUE TITLE
create a video guide

### ISSUE THREAD

**Issue by ghost** [en9inerd/tgeraser#12]
create a detailed video guide on how to use this tool. i have no experience in coding and because of it i have difficulties using this tool. i think i am not the only one, and creating a video guide will help people and also me to understand how to use this tool. i hope for your understanding.

**Comment by en9inerd** [comment]
@BibaGoddamn Thank you for your feedback. Unfortunately, creating a video guide is not in the plans and is unlikely to be in the future.
This tool was initially developed for personal use and assumes some familiarity with the command line. Could you please provide more details about the specific issues you're facing?
