### ISSUE TITLE
Remaining 1 messages can't be deleted without admin rights because they are service messages.

### ISSUE THREAD

**Issue by fqlx** [en9inerd/tgeraser#13]
Is there a way to view the remaining messages?  I'm curious to know which message could not be deleted.

```
====================================
= Deleting messages from 'Reth'... =
====================================

Deleted 0 messages of 1 in 'Reth' entity.
Remaining 1 messages can't be deleted without admin rights because they are service messages.
```

**Comment by en9inerd** [comment]
@fqlx tool doesn't provide functionality to display undeleted messages. Typically, service messages that can't be deleted without admin rights are related to users joining or leaving the chat. You can find them using the official client by searching for messages authored by you in the chat.
