### ISSUE TITLE
Trouble using wipe everything command

### ISSUE THREAD

**Issue by ramyrover** [en9inerd/tgeraser#14]
Maybe i have misinterpreted the meaning of the command, but i am looking to clear messages from both parties of a private message session. So far i have only been able to clear my own messages with no luck deleting the other entities sent messages. Please do inform if this is possible to clear the other entity messages.

Used command :  tgeraser session "xxx" -w --entity-type "user" && tgeraser session "xxx" --wipe-everything --entity-type "user"

**Comment by en9inerd** [comment]
@ramyrover Thank you for your feedback. Yeah you are right, It’s reasonable to delete entire chat history with revoke param (to delete messages from both sides) if entity is user. I thought I have this logic for user entity.
Anyway, I just released a fix for that, let me know if it works.
